# Generated by Django 3.2.6 on 2021-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('status', models.CharField(choices=[('done', 'done'), ('doing', 'doing'), ('todo', 'todo')], max_length=5, verbose_name='Status')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
